try:
    a = int('213g')
    print(a)
except ValueError:
    print('сталася помилка')
